DATA:
  data_folder: 'C:\projects\own_churn\DATA'
BUCKETS:
  user_logs: {'bucket_25': [0, 10, 100, 300, 500],
             'bucket_50': [0, 10, 100, 300],
             'bucket_75': [0, 10, 100, 200],
             'bucket_985': [0, 10, 100, 200],
             'bucket_100': [0, 10, 50, 100, 200, 400],
             'bucket_num_unq': [0, 10, 40, 100, 200, 300, 400],
             'bucket_total_sec': [0, 30, 60, 120, 180, 300, 600, 1200]}
NET:
  Dense:
    activation: relu
    transactions_structure: [7,32, 64]
    logs_structure: [5, 7, 10, 12]